[Bugfix] Fix LineString Error
`line-width` expects a `number`, otherwise the following error occurs:

```
Error: layers.postgis-preview.paint.line-width: number expected, string found
    at Object.mr [as emitValidationErrors] (validate_style.js:27)
    at Fe (style.js:43)
    at i._validate (style.js:976)
    at i.addLayer (style.js:564)
    at o.addLayer (map.js:1227)
    at Map.addJsonLayer (<anonymous>:156:16)
    at Map.componentWillReceiveProps (<anonymous>:130:27)
    at react-dom.js:5065
    at measureLifeCyclePerf (react-dom.js:4529)
    at ReactCompositeComponentWrapper.updateComponent (react-dom.js:5064)
```